[tool.poetry]
name = "plotano"
version = "0.0.0"
description = ""
authors = ["CambioML <wanwanaiai45@gmail.com>"]
license = "Apache"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
accelerate = "0.21.0"
bitsandbytes = "0.40.2"
einops = "0.6.1"
flask = "2.3.2"
flask-cors = "4.0.0"
pyngrok = "6.0.0"
scipy = "1.11.1"
torch = "2.0.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
